@extends('layouts/top10_layout')
@section('titolo_top_10','CENTROCAMPISTI')
@section('presentazione_sezione','This is the list of the 10 best strikers in the world. If you are looking for the star of your team you are in the right place!')
@section('citazione',"The midfield is the hearthbeat of a football team, it's the centre of the action, so you can't just do one thing.")
@section('citazione_autore','Casemiro')
@section('caratteristica','Assist')