@extends('layouts/top10_layout')
@section('titolo_top_10','DIFENSORI')
@section('presentazione_sezione','This is the list of the 10 best strikers in the world. If you are looking for the star of your team you are in the right place!')
@section('citazione',"In my teams, the goalie is the first attacker, and the striker the first defender.")
@section('citazione_autore','Johan Cruijff')
@section('caratteristica','Contrasti')